# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
    - "*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout to ${GITHUB_WORKSPACE}
        uses: actions/checkout@v2

      - name: Set Variables
        run: |
          echo "GIT_NUGET_URL=https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" >> $GITHUB_ENV
          echo "NUGET_URL=https://api.nuget.org/v3/index.json" >> $GITHUB_ENV
          echo "TAG_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      
      - name: Setup NuGet.exe for use with actions
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
        uses: NuGet/setup-nuget@v1.0.5
        with:
          # NuGet version to install. Can be `latest`, `preview`, a concrete version like `5.3.1`, or a semver range specifier like `5.x`.
          nuget-version: latest
          # NuGet API Key to configure.
          #nuget-api-key: # optional
          # Source to scope the NuGet API Key to.
          #nuget-api-key-source: # optional

      - name: Create NuGet Package
        run: nuget pack -NoDefaultExcludes -Version ${TAG_VERSION}
      
      - name: Push Package to GIT
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_API_KEY}}
        run: nuget push TheCodeAttic.Sitecore.HelixTemplates.${TAG_VERSION}.nupkg -Source ${GIT_NUGET_URL} -ApiKey  ${GITHUB_TOKEN}

      - name: Push Package to NuGet
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_API_KEY}}
        run: | 
          nuget setApiKey ${NUGET_TOKEN}
          nuget push TheCodeAttic.Sitecore.HelixTemplates.${TAG_VERSION}.nupkg -Source ${NUGET_URL}
